name: Scrape CalCareers Daily

on:
  schedule:
    - cron: '0 2 * * *'  # every day at 2 AM UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install beautifulsoup4 requests
      - name: Run scraper
        run: python scraper.py
      - name: Commit and push updated jobs.json
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}
          git add jobs.json
          git commit -m "Update job listings" || echo "No changes to commit"
          git push
